<a href="https://colab.research.google.com/github/Kggzzz/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# numpy array

In [3]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

ตัวอย่างการสร้าง numpy arrayตามสไลด์แลคเชอร์

In [4]:
np1=np.array([[1,2],[3,5],[2,0],[4,5]])
np1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [5]:
np1.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [6]:
np1[0,:]

array([1, 2])

## HW 6 
สร้าง Distance metrix (Eucluidean) ของ np2
โดยสร้าง function สำหรับคำนวณ Manhattan  Distance และ Euclidean Distance 

def Euclidean(data1,data2) :
#process 
return dist

In [7]:
def manhattan(data1,dat2):
    disxtX = data1[0]-data2[0]
    return distX

In [8]:
import math

In [9]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0])
    distY = abs(data1[1]-data2[1])
    return distX+distY

In [10]:
Manhattan(np1[0,:],np1[1,:])

5

In [11]:
dist_mat=np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
5*np.ones((4,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
for i in range(4):
    for j in range(4):
        dist_mat[i,j]=Manhattan(np1[i,:],np1[j,:])

dist_mat

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [14]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [23]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j]=Euclidean(np2[i,:],np2[j,:])
dist_math1 

NameError: ignored